### PR TITLE
Linux Build

### PR DESCRIPTION
**Pull request by kaytotes**
Finding this tool has seriously saved me a shed load of work so might as well give back what little I can.

Simply adds an equivalent to the `build_release.bat` that works for generating a Linux build. 

I haven't tested all of the modules just DBC import to DB and export back to DBC.

### Usage

`./build_release.sh`

It then spits out correctly into the `Build` directory.

I haven't bothered with also re-writing the `.bat` files for each module eg `createdbc_run.bat` as these can pretty easily be ran from terminal anyway.

Eg:

```
./FreecraftCore.DBC.CreateDatabase
FreecraftCore Copyright (c) 2020 Glader/HelloKitty
Running FreecraftCore.DBCTools CreateDatabase.
Will create tables and database if they do not exist.
Populating table for DBC: SpellDuration
Populating table for DBC: SkillLine
Populating table for DBC: ChrClasses
Populating table for DBC: FactionGroup
Populating table for DBC: QuestInfo
Populating table for DBC: Achievement_Criteria
Populating table for DBC: Achievement_Category
Populating table for DBC: CinematicCamera
Populating table for DBC: CreatureDisplayInfo
Populating table for DBC: QuestSort
Populating table for DBC: SpellCastTimes
Populating table for DBC: FactionTemplate
Populating table for DBC: Faction
Populating table for DBC: AreaTrigger
Populating table for DBC: CharBaseInfo
Populating table for DBC: SoundEntries
Populating table for DBC: FootprintTextures
Populating table for DBC: GameTips
Populating table for DBC: Spell
Populating table for DBC: Languages
Populating table for DBC: ParticleColor
Populating table for DBC: CreatureSoundData
Populating table for DBC: SpellRange
Populating table for DBC: CreatureDisplayInfoExtra
Populating table for DBC: CameraShakes
Populating table for DBC: NamesProfanity
Populating table for DBC: CreatureType
Populating table for DBC: UnitBloodLevels
Populating table for DBC: CinematicSequences
Populating table for DBC: AreaTable
Populating table for DBC: SkillLineAbility
Populating table for DBC: LoadingScreens
Populating table for DBC: SpellRadius
Populating table for DBC: ChrRaces
Populating table for DBC: SkillLineCategory
Populating table for DBC: GameObjectDisplayInfo
Populating table for DBC: NPCSounds
Populating table for DBC: ItemDisplayInfo
Populating table for DBC: ObjectEffectPackage
Populating table for DBC: ServerMessages
Populating table for DBC: Map
Populating table for DBC: SpellItemEnchantment
Populating table for DBC: Item
Populating table for DBC: LanguageWords
Populating table for DBC: CharTitles
Populating table for DBC: Achievement
Populating table for DBC: UnitBlood
Populating table for DBC: QuestXP
Populating table for DBC: SpellIcon
Populating table for DBC: CreatureModelData
Populating table for DBC: SpellDifficulty
Finished. Press any key!

```

### CODE REVIEW

**Comment by HelloKitty** [comment]
Oooh awesome! I am surprised someone is using this, I figured I'd be the sole user. Do you have any feedback on the project? I don't know much about Linux but seems good to me! I will merge =).

**Comment by kaytotes** [comment]
My only real feedback is please keep this up as the scene needs modern tooling that’s cross platform. 

If there are any docs available for adding new DBC types that would be great. Been looking at a couple of your old commits to figure out the rough process.

My intent is to add support for CharStartOutfit as my custom classes are nude on the character create screen without it but that’s not a huge rush.

**Comment by HelloKitty** [comment]
@kaytotes It's a slightly complicated process, but the DBC model types are implemented here; https://github.com/FreecraftCore/FreecraftCore.Library/tree/master/src/FreecraftCore.API.Data/DBC/Entry

Unfortunately I implement DBC types as I end up needing them, as I build my Unity3D client implementation. Since I'm a one-man-band I have to prioritize time spent implementing things and many DBCs are just low on the TODO list =(. As I implement them, they'll be available though!

FreecraftCore.Library is also unfortunately not accepting PRs at this time either.

**Comment by kaytotes** [comment]
Well if you get round to that one i'd much appreciate it and if you have some sort of patreon or paypal would be happy to contribute for your time.

**Pull request merged**
